services:
  app:
    image: 'airbookings:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"

  db:
    image: 'postgres:16.2'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - C:\Programming\Spring\airbookings_postgres_data:/var/lib/postgresql/data
        - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"